# Dockerfile
FROM php:8.2.0

# Copy composer.lock and composer.json
COPY composer.json /var/www/

# Set working directory
WORKDIR /var/www

# Install dependencies
RUN apt-get update && apt-get install -y \
    ca-certificates \
    build-essential \
    libpng-dev \
    libwebp-dev \
    libxpm-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    locales \
    zip \
    jpegoptim optipng pngquant gifsicle \
    vim \
    unzip \
    git \
    curl libcurl4 \
    libzip-dev libonig-dev


COPY ./docker/php.ini /usr/local/etc/php/conf.d/laravel-custom.ini


# Install Node.js (versi 20 LTS) + pnpm
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs \
    && npm install -g pnpm

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install extensions
RUN docker-php-ext-install pdo_mysql mbstring zip exif pcntl
RUN docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp --with-xpm
RUN docker-php-ext-install -j$(nproc) gd

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copy existing application directory contents
COPY . /var/www

# Install composer dependencies
RUN rm /var/www/composer.lock
RUN composer install --no-interaction --no-scripts --no-dev --prefer-dist

# Install frontend dependencies
RUN pnpm install --force

# Build frontend assets
RUN pnpm run build

# Expose port 8080 and start project
EXPOSE 8080
CMD php artisan serve --host=0.0.0.0 --port=8080
